name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    name: "Test on Node:${{ matrix.node-version }} OS:${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10, 12, 14]
        os: [ubuntu-latest]
        include:
          - os: windows-latest
            node-version: 14
    steps:
      - uses: actions/checkout@v2
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "node_modules"
          key: ${{ runner.os }}-node-v${{ matrix.node-version }}-yarn-${{ hashFiles('yarn.lock') }}
      - run: yarn --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn lint
        if: matrix.os != 'windows-latest'
      - run: yarn typecheck
      - run: yarn test --coverage
      - run: npx codecov
        if: github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-latest' && matrix.node-version == 14
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: test
    if: contains(github.ref, 'tags/v')
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "node_modules"
          key: ${{ runner.os }}-node-v12-yarn-${{ hashFiles('yarn.lock') }}
      - run: yarn --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
